### ISSUE TITLE
libevent 2.2 release checklist

### ISSUE THREAD

**Issue by azat** [libevent/libevent#1094]
**Release Pull Request - #1380**

### Release checklist
- [ ] update changelog
- [ ] bump versions
- [ ] release with github login tags

### CI
- [x] [mingw cmake failures](https://github.com/libevent/libevent/runs/1088210241) - #1267, #1258
- [ ] #1207, #1300
- [x] ~~run [libevent-extras](https://github.com/libevent/libevent-extras) tests~~ - no need to, github actions contains everything and even more nowadays

### Checklist
- [x] #795 
- [x] #1006
- [x] #1264
- [x] OpenSSL 3.0 (#1250, #1233, #1212)
- [x] mbedTLS 3.0 (#1299)
- [x] #1264 
- [x] #1342
- [x] #1221/ #1397
- [x] #1441
- [x] #1405
- [x] #1385

### Optional
- [ ] #1038
- [ ] #779
- [ ] #777 
- [ ] #1453

**Comment by julio202020** [comment]
Gracias

**Comment by tristan957** [comment]
@azat in this comment (https://github.com/libevent/libevent/issues/1282#issuecomment-1171578504), you said "one more release". Does that mean libevent will go unmaintained after the next release or were you just referring to the 2.2 release when you said that.

**Comment by primeuser25** [comment]
> ### Release checklist
> * [ ]  update changelog
> * [ ]  bump versions
> * [ ]  release with github login tags
> 
> ### CI
> * [x]  [mingw cmake failures](https://github.com/libevent/libevent/runs/1088210241) - [[Windows CI] Fix failing mingw build tasks. #1267](https://github.com/libevent/libevent/pull/1267), [ci: fix mingw build #1258](https://github.com/libevent/libevent/pull/1258)
> * [ ]  [CI: mingw cmake failures (Exit code 0xc0000135) #1207](https://github.com/libevent/libevent/issues/1207), [ci: fix MinGW build with cmake (Exit code 0xc0000135) #1300](https://github.com/libevent/libevent/pull/1300)
> * [ ]  run [libevent-extras](https://github.com/libevent/libevent-extras) tests
> 
> ### Issues
> * [x]  [evhttp: eliminate internal fd #795](https://github.com/libevent/libevent/issues/795)
> * [x]  [wepoll: Use wepoll to light up the epoll backend on Windows #1006](https://github.com/libevent/libevent/pull/1006)
> * [ ]  [Dedicated event for EPOLLHUP, EPOLLERR #1038](https://github.com/libevent/libevent/issues/1038)
> * [ ]  [evsig_base is thread unsafe #779](https://github.com/libevent/libevent/issues/779)
> * [ ]  [event_debug_mode_too_late is thread unsafe #777](https://github.com/libevent/libevent/issues/777)
> * [ ]  [Windows: Add ProcessSocketNotifications backend #1264](https://github.com/libevent/libevent/pull/1264)
> * [x]  OpenSSL 3.0 ([tests failing (clang-git, openssl-git, zlib-git)  #1250](https://github.com/libevent/libevent/issues/1250), [Problems with OpenSSL 3.0 #1233](https://github.com/libevent/libevent/issues/1233), [2.1.12: test suite is failing (with openssl 3.0) #1212](https://github.com/libevent/libevent/issues/1212))
> * [x]  mbedTLS 3.0 ([Initial Mbed-TLS 3 support to get the GitHub Actions working again #1299](https://github.com/libevent/libevent/pull/1299))
> * [ ]  [Use GNUInstallDirs for mapping installation directories #1221](https://github.com/libevent/libevent/pull/1221)
> * [ ]  [Windows: Add ProcessSocketNotifications backend #1264](https://github.com/libevent/libevent/pull/1264)

**Comment by Neustradamus** [comment]
Dear @libevent team, @azat,

It is possible to have a new release build after more two years?

The last 2.1.12 (2020-07-05):
- https://github.com/libevent/libevent/releases

Thanks in advance.

PS: It follows my original ticket here: https://github.com/libevent/libevent/issues/1365, @stefansjfw here too: https://github.com/libevent/libevent/issues/1282, and @fjahr here too: https://github.com/libevent/libevent/issues/1024.

**Comment by azat** [comment]
>@azat in this comment (https://github.com/libevent/libevent/issues/1282#issuecomment-1171578504), you said "one more release". Does that mean libevent will go unmaintained after the next release or were you just referring to the 2.2 release when you said that?

@tristan957 I hope not since I've already found a co-maintainer.

P.S. sorry I thought that I replied to this comment, but apparently I was wrong.

**Comment by azat** [comment]
>It is possible to have a new release build after more two years?

@Neustradamus yes, this is in my todo list, you can track the progress in this issue.

**Comment by Neustradamus** [comment]
@azat: Have you progressed on it?

**Comment by Neustradamus** [comment]
@azat: It will be good for Debian 12?

**Comment by azat** [comment]
>@azat: Have you progressed on it?

I wish...

>@azat: It will be good for Debian 12?

This new release likely compatible with previous, only deprecated long-time-ago things may not work (for example few APIs with global base).
As for libevent in distros, likely the major version can be upgraded even inside one distro release, though I'm not sure here (since it may have some concerns), we can ask package maintainer here, @babelouest can you comment on this please?

**Comment by babelouest** [comment]
Hi @azat ,

Unfortunately, it's very unlikely for the next release to be available in Debian 12, even if libevent 2.2 is released tomorrow, Debian Bookworm is too close to the [freeze state](https://release.debian.org/bookworm/freeze_policy.html) and libevent has a lot of dependencies.

But I can package libevent 2.2 in experimental and give feedbacks with the transition when needed.

**Comment by Neustradamus** [comment]
Dear @libevent team, @azat,

It is possible to create a new release before Debian 13 freeze like I have requested you in my ticket?
- https://github.com/libevent/libevent/issues/1760

Already 4 years and 6 months since 2.1.12 (2020-07-05).

Next Debian 14 will be in 2027, if no new version, it will be very obsolete more 6 years and 6 months.

Thanks in advance.

Linked to my initial request done 2022-10-29:
- https://github.com/libevent/libevent/issues/1365

Linked to:
- https://github.com/libevent/libevent/issues/1094
- https://github.com/libevent/libevent/pull/1380
- https://github.com/libevent/libevent/issues/1512
